// app/api/muizza-fashion/data.ts
//
// Single source of truth for the product catalogue.
// Both /api/muizza-fashion/route.ts  (list)
// and  /api/muizza-fashion/product/route.ts  (by slug)
// import PRODUCTS from here.
//
// To swap in a database, replace this file's export with an async
// loader and update the callers accordingly.

import type { MFProduct } from '@/lib/muizza.types';

export const PRODUCTS: MFProduct[] = [

  // ── Abayas ──────────────────────────────────────────────────────────────────
  {
    id: 'abaya-1',
    slug: 'classic-embroidered-abaya',
    name: 'Classic Embroidered Abaya',
    category: 'abaya',
    categoryLabel: 'Abayas',
    image: '/store-icon/Muizza-Fashion/products/design-01.jpeg',
    basePrice: 4500,
    estimatedDays: 7,
    fabric: 'Nida, Crepe, Georgette',
    occasion: 'Daily, Formal',
    description:
      'A timeless silhouette with delicate hand-embroidery along the cuffs and neckline. Flows beautifully in Nida and Crepe — lightweight enough for daily wear, polished enough for formal occasions.',
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    tags: ['bestseller', 'modest'],
  },
  {
    id: 'abaya-2',
    slug: 'open-front-butterfly-abaya',
    name: 'Open-Front Butterfly Abaya',
    category: 'abaya',
    categoryLabel: 'Abayas',
    image: '/store-icon/Muizza-Fashion/products/design-02.jpeg',
    basePrice: 5200,
    estimatedDays: 7,
    fabric: 'Nida, Chiffon',
    occasion: 'Party, Formal',
    description:
      'Dramatic wide sleeves that flutter with every step. The open-front style pairs perfectly over an inner slip. Available in Nida for structure or Chiffon for a softer drape.',
    rating: 4.7,
    reviewCount: 17,
    featured: false,
    tags: ['trending'],
  },
//   {
//     id: 'abaya-3',
//     slug: 'lace-trim-abaya',
//     name: 'Lace-Trim Casual Abaya',
//     category: 'abaya',
//     categoryLabel: 'Abayas',
//     image: 'https://images.unsplash.com/photo-1614093302611-8efc673b8ea1?w=600&q=80',
//     basePrice: 3900,
//     estimatedDays: 6,
//     fabric: 'Crepe, Nida',
//     occasion: 'Daily, Casual',
//     description:
//       'Understated everyday abaya with a subtle lace trim at the hem and sleeves. Relaxed fit, easy care Crepe fabric.',
//     rating: 4.5,
//     reviewCount: 9,
//     featured: false,
//   },

//   // ── Gowns ────────────────────────────────────────────────────────────────────
//   {
//     id: 'gown-1',
//     slug: 'floral-layered-maxi-gown',
//     name: 'Floral Layered Maxi Gown',
//     category: 'gown',
//     categoryLabel: 'Gowns',
//     image: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=600&q=80',
//     basePrice: 6500,
//     estimatedDays: 10,
//     fabric: 'Organza, Satin, Chiffon',
//     occasion: 'Party, Wedding',
//     description:
//       'Romantic layered skirt with a fitted bodice. The Organza overlay catches the light and adds volume without weight. A favourite for walimas and evening events.',
//     rating: 4.6,
//     reviewCount: 11,
//     featured: true,
//   },
//   {
//     id: 'gown-2',
//     slug: 'evening-shimmer-gown',
//     name: 'Evening Shimmer Gown',
//     category: 'gown',
//     categoryLabel: 'Gowns',
//     image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',
//     basePrice: 8500,
//     estimatedDays: 12,
//     fabric: 'Velvet, Satin',
//     occasion: 'Wedding, Formal',
//     description:
//       'Luxurious floor-length gown in rich Velvet or Satin. Fitted through the bodice with a subtle flare — an evening statement piece.',
//     rating: 4.9,
//     reviewCount: 7,
//     featured: false,
//     tags: ['premium'],
//   },
//   {
//     id: 'gown-3',
//     slug: 'modest-a-line-gown',
//     name: 'Modest A-Line Maxi Gown',
//     category: 'gown',
//     categoryLabel: 'Gowns',
//     image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80',
//     basePrice: 5800,
//     estimatedDays: 9,
//     fabric: 'Chiffon, Georgette',
//     occasion: 'Party, Casual',
//     description:
//       'Clean A-line silhouette in flowing Chiffon or Georgette. High neckline, full sleeves, comfortable for all-day wear at celebrations.',
//     rating: 4.4,
//     reviewCount: 13,
//     featured: false,
//   },

//   // ── Kurtis ───────────────────────────────────────────────────────────────────
//   {
//     id: 'kurti-1',
//     slug: 'cotton-straight-kurti',
//     name: 'Cotton Straight Kurti Set',
//     category: 'kurti',
//     categoryLabel: 'Kurtis',
//     image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80',
//     basePrice: 3200,
//     estimatedDays: 5,
//     fabric: 'Cotton, Linen',
//     occasion: 'Casual, Office',
//     description:
//       'Breathable Cotton or Linen straight kurti with matching dupatta and pants. Clean lines, side pockets, easy everyday comfort.',
//     rating: 4.7,
//     reviewCount: 18,
//     featured: false,
//   },
//   {
//     id: 'kurti-2',
//     slug: 'embroidered-anarkali-kurti',
//     name: 'Embroidered Anarkali Kurti',
//     category: 'kurti',
//     categoryLabel: 'Kurtis',
//     image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
//     basePrice: 4100,
//     estimatedDays: 6,
//     fabric: 'Rayon, Cotton',
//     occasion: 'Casual, Party',
//     description:
//       'Flared Anarkali silhouette with delicate embroidery at the yoke. Pairs with churidar or palazzo. A perennial bestseller.',
//     rating: 4.6,
//     reviewCount: 21,
//     featured: false,
//     tags: ['bestseller'],
//   },

//   // ── Blouses ──────────────────────────────────────────────────────────────────
//   {
//     id: 'blouse-1',
//     slug: 'silk-puff-sleeve-blouse',
//     name: 'Silk Puff-Sleeve Blouse',
//     category: 'blouse',
//     categoryLabel: 'Blouses',
//     image: 'https://images.unsplash.com/photo-1485462537746-965f33f4ae91?w=600&q=80',
//     basePrice: 2400,
//     estimatedDays: 4,
//     fabric: 'Silk, Satin',
//     occasion: 'Office, Casual',
//     description:
//       'Structured puff sleeves in Silk or Satin. Tucks neatly or worn loose. A versatile piece that elevates any outfit.',
//     rating: 4.5,
//     reviewCount: 8,
//     featured: false,
//   },
//   {
//     id: 'blouse-2',
//     slug: 'embroidered-collar-blouse',
//     name: 'Embroidered Collar Blouse',
//     category: 'blouse',
//     categoryLabel: 'Blouses',
//     image: 'https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=600&q=80',
//     basePrice: 2800,
//     estimatedDays: 4,
//     fabric: 'Cotton, Linen',
//     occasion: 'Casual, Party',
//     description:
//       'Peter Pan collar with hand-embroidered edge detailing. Relaxed fit in breathable Cotton or Linen.',
//     rating: 4.3,
//     reviewCount: 5,
//     featured: false,
//   },

//   // ── Skirts ───────────────────────────────────────────────────────────────────
//   {
//     id: 'skirt-1',
//     slug: 'pleated-midi-skirt',
//     name: 'Pleated Midi Skirt',
//     category: 'skirt',
//     categoryLabel: 'Skirts',
//     image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80',
//     basePrice: 2900,
//     estimatedDays: 4,
//     fabric: 'Chiffon, Georgette',
//     occasion: 'Casual, Party',
//     description:
//       'Knife-pleated midi skirt with a comfortable elasticated waist. Moves beautifully in Chiffon or Georgette.',
//     rating: 4.4,
//     reviewCount: 12,
//     featured: false,
//   },
//   {
//     id: 'skirt-2',
//     slug: 'tiered-floral-maxi-skirt',
//     name: 'Tiered Floral Maxi Skirt',
//     category: 'skirt',
//     categoryLabel: 'Skirts',
//     image: 'https://images.unsplash.com/photo-1577900232427-18219b9166a0?w=600&q=80',
//     basePrice: 3400,
//     estimatedDays: 5,
//     fabric: 'Cotton, Rayon',
//     occasion: 'Casual, Daily',
//     description:
//       'Three-tier maxi skirt with a relaxed boho feel. Cotton or Rayon, printed or solid on request.',
//     rating: 4.6,
//     reviewCount: 9,
//     featured: false,
//   },

//   // ── Suits ────────────────────────────────────────────────────────────────────
//   {
//     id: 'suit-1',
//     slug: 'embroidered-salwar-suit',
//     name: 'Embroidered Salwar Suit',
//     category: 'suit',
//     categoryLabel: 'Suits',
//     image: 'https://images.unsplash.com/photo-1622519407650-3df9883f76a5?w=600&q=80',
//     basePrice: 5500,
//     estimatedDays: 8,
//     fabric: 'Cotton, Georgette, Silk',
//     occasion: 'Party, Formal, Eid',
//     description:
//       'Three-piece salwar suit with embroidered kameez, matching bottoms and dupatta. A go-to for Eid, parties and formal occasions.',
//     rating: 4.8,
//     reviewCount: 30,
//     featured: true,
//     tags: ['bestseller', 'eid'],
//   },
//   {
//     id: 'suit-2',
//     slug: 'palazzo-suit-set',
//     name: 'Palazzo Suit Set',
//     category: 'suit',
//     categoryLabel: 'Suits',
//     image: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4de0?w=600&q=80',
//     basePrice: 4800,
//     estimatedDays: 7,
//     fabric: 'Rayon, Cotton',
//     occasion: 'Casual, Party',
//     description:
//       'Wide-leg palazzo pants with matching kurti top. Comfortable, modest and stylish for everyday and light occasions.',
//     rating: 4.5,
//     reviewCount: 15,
//     featured: false,
//   },

//   // ── Casual Wear ──────────────────────────────────────────────────────────────
//   {
//     id: 'casual-1',
//     slug: 'everyday-cotton-maxi',
//     name: 'Everyday Cotton Maxi Dress',
//     category: 'casual',
//     categoryLabel: 'Casual Wear',
//     image: 'https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=600&q=80',
//     basePrice: 2600,
//     estimatedDays: 4,
//     fabric: 'Cotton',
//     occasion: 'Daily, Casual',
//     description:
//       'Easy-wear full-length Cotton dress with a relaxed silhouette. Side pockets, breathable fabric, wash-and-wear convenience.',
//     rating: 4.6,
//     reviewCount: 27,
//     featured: false,
//     tags: ['everyday'],
//   },
//   {
//     id: 'casual-2',
//     slug: 'linen-loungewear-set',
//     name: 'Linen Co-ord Loungewear Set',
//     category: 'casual',
//     categoryLabel: 'Casual Wear',
//     image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80',
//     basePrice: 3100,
//     estimatedDays: 5,
//     fabric: 'Linen, Cotton',
//     occasion: 'Casual, Home',
//     description:
//       'Matching top and wide-leg trouser set in cool Linen or Cotton. Relaxed enough for home, presentable enough for errands.',
//     rating: 4.5,
//     reviewCount: 14,
//     featured: false,
//   },

//   // ── Bridal ───────────────────────────────────────────────────────────────────
//   {
//     id: 'bridal-1',
//     slug: 'bridal-lehenga-set',
//     name: 'Bridal Lehenga Choli Set',
//     category: 'bridal',
//     categoryLabel: 'Bridal',
//     image: 'https://images.unsplash.com/photo-1610189352649-3ded8c9ef08a?w=600&q=80',
//     basePrice: 18000,
//     estimatedDays: 14,
//     fabric: 'Silk, Velvet, Organza',
//     occasion: 'Wedding, Nikah',
//     description:
//       'Fully hand-crafted bridal lehenga with intricate zari and sequin embroidery. Includes choli blouse and dupatta. Every piece is one-of-a-kind.',
//     rating: 5.0,
//     reviewCount: 6,
//     featured: true,
//     tags: ['premium', 'bridal'],
//   },
//   {
//     id: 'bridal-2',
//     slug: 'nikah-gown',
//     name: 'Modest Nikah Gown',
//     category: 'bridal',
//     categoryLabel: 'Bridal',
//     image: 'https://images.unsplash.com/photo-1537832816519-689ad163238b?w=600&q=80',
//     basePrice: 14500,
//     estimatedDays: 12,
//     fabric: 'Satin, Lace, Chiffon',
//     occasion: 'Nikah, Wedding',
//     description:
//       'Elegant floor-length nikah gown with lace overlay and long sleeves. Modest, refined, and unforgettable.',
//     rating: 4.9,
//     reviewCount: 4,
//     featured: false,
//     tags: ['premium', 'bridal'],
//   },
];